const THEME = "solid";

export const iconMap = {
    potentialPositionNumberOne: "fa-kit fa-solid-square-1-circle-question",
    potentialPositionTopTwelve: "fa-kit fa-solid-star-circle-question",
    isLoved: "fa-solid fa-heart",
    hasTopRbOpportunity: "fa-solid fa-weight-hanging",
    hasCampHype: "fa-solid fa-campground",
    hasSamUpside: "fa-solid fa-rocket-launch",
    isGoalLineBack: "fa-solid fa-crow",
    isEfficientRunner: "fa-solid fa-person-running-fast",
    isPotentialBust: "fa-solid fa-thumbs-down",
    isLeapYearCandidate: "fa-solid fa-frog",
    hasNegativeSamUpside: "fa-regular fa-arrow-trend-down",
    isFirstRoundRbOrWr: "fa-solid fa-baby",
    hasRookieQb: "fa-solid fa-person-breastfeeding",
    hasNegativeCampBuzz: "fa-solid fa-poop",
    hasLowRyoeAndLowEpa: "fa-solid fa-traffic-cone",
    isFightingToStart: "fa-solid fa-bench-tree",
    isMainlySlotPlayer: "fa-solid fa-slot-machine",
    isNotGoalLineBack: "fa-solid fa-stomach",
    projectedNegativeRegression: "fa-solid fa-arrow-down",
    isValuableHandcuff: "fa-solid fa-handcuffs",
    myTargets: "fa-solid fa-bullseye",
};
